ARG REGISTRY=harbor.sunmoonai.com:30443/k8s-images

FROM ${REGISTRY}/nginx:stable-alpine AS run

COPY dist /usr/share/nginx/html
COPY mybuild/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
