// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/reference": {
    params: {};
  };
  "/rich-reference": {
    params: {};
  };
  "/info/crawl": {
    params: {};
  };
  "/forbidden": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/reference" | "/rich-reference" | "/info/crawl" | "/forbidden" | "/*";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/protected-layout.tsx": {
    id: "routes/protected-layout";
    page: "/" | "/reference" | "/rich-reference" | "/info/crawl" | "/forbidden";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/reference.tsx": {
    id: "routes/reference";
    page: "/reference";
  };
  "./routes/rich-reference.tsx": {
    id: "routes/rich-reference";
    page: "/rich-reference";
  };
  "./routes/info-crawl.tsx": {
    id: "routes/info-crawl";
    page: "/info/crawl";
  };
  "./routes/forbidden.tsx": {
    id: "routes/forbidden";
    page: "/forbidden";
  };
  "./routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/protected-layout": typeof import("./app/./routes/protected-layout.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/reference": typeof import("./app/./routes/reference.tsx");
  "routes/rich-reference": typeof import("./app/./routes/rich-reference.tsx");
  "routes/info-crawl": typeof import("./app/./routes/info-crawl.tsx");
  "routes/forbidden": typeof import("./app/./routes/forbidden.tsx");
  "routes/not-found": typeof import("./app/./routes/not-found.tsx");
};